CREATE TABLE IF NOT EXISTS dispositivos (
    id SERIAL PRIMARY KEY,
    mac TEXT UNIQUE NOT NULL,
    criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultima_deteccao TIMESTAMP NOT NULL,
    total_repeticoes INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS passagens (
    id SERIAL PRIMARY KEY,
    local TEXT NOT NULL,
    aparelho TEXT NOT NULL,
    data TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dispositivo_id INTEGER NOT NULL REFERENCES dispositivos(id) ON DELETE CASCADE,
    ultima_deteccao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);